2023-06-15 19:11:13,474 - root - INFO - Logger Inititated
2023-06-15 19:11:18,236 - root - INFO - Logger Inititated
2023-06-15 19:11:21,688 - root - INFO - [main][signup][Request Landed] 
2023-06-15 19:11:21,765 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2023-06-15 19:11:21,774 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2023-06-15 19:11:21,879 - urllib3.connectionpool - DEBUG - https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
2023-06-15 19:11:23,579 - root - INFO - [generateSupportFields][signUpSupports][Completed user support data][data] {'email': 'test@testmail.com', 'password': 'Test@123', 'phone': '12345678', 'verified': '0', 'role': '3', 'dept': 'EE', 'class': 'EE23', 'id': '3490323161', 'user_id': 'ST_86_143845530', 'last_updated_time': '143845530'} 
2023-06-16 12:32:21,512 - root - INFO - Logger Inititated
2023-06-16 12:32:35,042 - root - INFO - [main][signup][Request Landed] 
2023-06-16 12:32:35,043 - root - ERROR - [generateSupportFields][Exception in signUpSupports] type object 'datetime.datetime' has no attribute 'datetime'
Traceback (most recent call last):
  File "/Users/dev-15158/codingfiles/VScode files/Project Files/Pyhton projects/FastAPI/StudentManagementSystem/Commons/generateSupportFields.py", line 17, in signUpSupports
    currentDateTime = datetime.datetime.now()
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2023-06-16 12:32:55,719 - root - INFO - Logger Inititated
2023-06-16 12:32:57,578 - root - INFO - [main][signup][Request Landed] 
2023-06-16 12:32:57,668 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2023-06-16 12:32:57,679 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2023-06-16 12:32:57,785 - urllib3.connectionpool - DEBUG - https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
2023-06-16 12:32:58,274 - root - INFO - [generateSupportFields][signUpSupports][Completed user support data][data] {'email': 'test@testmail.com', 'password': 'Test@123', 'phone': '12345678', 'verified': '0', 'role': '3', 'dept': 'EE', 'class': 'EE2023', 'id': '349032023161', 'user_id': 'ST_61_154688643', 'last_updated_time': '2023-06-16 12:32:57.578570'} 
2023-06-16 12:46:30,889 - root - INFO - Logger Inititated
2023-06-16 12:47:10,246 - root - INFO - Logger Inititated
2023-06-17 14:29:03,165 - root - INFO - Logger Inititated
2023-06-17 14:31:01,707 - root - INFO - Logger Inititated
2023-06-17 14:31:07,897 - root - INFO - [main][signup][Request Landed] 
2023-06-17 14:31:38,053 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2023-06-17 14:31:38,073 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2023-06-17 14:31:38,186 - urllib3.connectionpool - DEBUG - https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
2023-06-17 14:31:38,566 - root - INFO - [generateSupportFields][signUpSupports][Completed user support data][data] {'email': 'test@testmail.com', 'password': 'Test@123', 'phone': '12345678', 'verified': '0', 'role': '3', 'dept': 'EE', 'class': 'EE2023', 'id': '349032023161', 'user_id': 'ST_40_188004984', 'last_updated_time': '2023-06-17 14:31:07.898008'} 
2023-06-17 14:31:38,583 - root - INFO - [accountDB][createAccount][Table Created]
2023-06-17 14:31:38,588 - root - INFO - [accountDB][createAccount][Data Inserted in Account Table]
2023-06-17 14:31:38,599 - root - INFO - [accountDB][createAccount][Password Saved in Password Table]
2023-06-17 14:31:54,291 - root - INFO - Logger Inititated
2023-06-17 14:33:17,193 - root - INFO - Logger Inititated
2023-06-17 14:33:22,648 - root - INFO - Logger Inititated
2023-06-17 14:33:27,985 - root - INFO - [main][signup][Request Landed] 
2023-06-17 14:33:58,084 - google.auth.transport.requests - DEBUG - Making request: POST https://oauth2.googleapis.com/token
2023-06-17 14:33:58,093 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
2023-06-17 14:33:58,189 - urllib3.connectionpool - DEBUG - https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
2023-06-17 14:33:58,536 - root - INFO - [generateSupportFields][signUpSupports][Completed user support data][data] {'email': 'test@testmail.com', 'password': 'Test@123', 'phone': '12345678', 'verified': '0', 'role': '3', 'dept': 'EE', 'class': 'EE2023', 'id': '349032023161', 'user_id': 'ST_55_188144953', 'last_updated_time': '2023-06-17 14:33:27.985352'} 
2023-06-17 14:33:58,536 - root - INFO - [accountDB][createAccount][Table Created]
2023-06-17 14:33:58,540 - root - ERROR - [DBOperations][Exception in __insertIntoTableTemplate] UNIQUE constraint failed: AccountsData.id
Traceback (most recent call last):
  File "/Users/dev-15158/codingfiles/VScode files/Project Files/Pyhton projects/FastAPI/StudentManagementSystem/SQLDB/DBOperations.py", line 67, in __insertIntoTable
    cursor.execute(query, values)
sqlite3.IntegrityError: UNIQUE constraint failed: AccountsData.id
2023-06-17 14:33:58,540 - root - INFO - [accountDB][createAccount][Data Inserted in Account Table]
2023-06-17 14:33:58,546 - root - INFO - [accountDB][createAccount][Password Saved in Password Table]
